### ISSUE TITLE
Gem Not Loading

### ISSUE THREAD

**Issue by daBee** [alchaplinsky/gen-ai#5]
Ruby 3.2.2, this gem is not loading:

```
begin
  require 'gen-ai'
  puts 'Gem is loaded!'
rescue LoadError
  puts 'Gem is not loaded!'
end
```

Shows up in `Gemfile` and `Gemfile.lock` but it's not loading for some reason.

**Comment by daBee** [comment]
Works!   But...Bundler.require doesn't load it.

**Comment by alchaplinsky** [comment]
Fix is now on main branch.
